export const roomData = [
  // yuka floor 床 - kabe wall 壁
  [
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
  ],
  [
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
  ],
  [
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
  ],
  [
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
  ],
  [
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
  ],
  [
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
  ],
  [
    { name: `Tile`, icon: "壁" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "床" },
    { name: `Tile`, icon: "壁" },
  ],
];
